{% set name = "daft" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daft-{{ version }}.tar.gz
  sha256: 3e77e0389ca539a5741a906bcdcaae462b68261d06b960b0c04498b695d312e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=30.3.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy

test:
  imports:
    - daft
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://daft-pgm.org
  summary: PGM rendering at its finest
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - maresb
