{% set name = "daft" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daft-{{ version }}.tar.gz
  sha256: b32620eef055a51f40e899bd11db6b4c8f4790d019d2e88f8f893150f2673598

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=30.3.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy

test:
  imports:
    - daft
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://daft-pgm.org
  summary: PGM rendering at its finest
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - maresb
